app:
  environment: ${APP_ENVIRONMENT:production}
  auth:
    mode: ${APP_AUTH_MODE:DATABASE}
  seed:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    pt.rucodel.productionplanning: INFO
