package pt.rucodel.productionplanning.domain;

public enum TelegramConversationState {
    AWAITING_DRIVER_NAME,
    IDLE,
    AWAITING_CUSTOMER,
    AWAITING_CUSTOMER_NAME,
    AWAITING_CUSTOMER_SELECTION,
    AWAITING_NEW_CUSTOMER_CONFIRMATION,
    AWAITING_NEW_CUSTOMER_DETAILS,
    AWAITING_NEW_CUSTOMER_FINAL_CONFIRMATION,
    AWAITING_BIPARTITE_QUANTITY,
    AWAITING_WASHED_QUANTITY,
    AWAITING_NORMAL_QUANTITY,
    AWAITING_FACTORY_DROPOFF_DATE,
    AWAITING_FACTORY_DROPOFF_SLOT,
    AWAITING_READY_DATE,
    AWAITING_FACTORY_PICKUP_SLOT,
    AWAITING_NOTES,
    AWAITING_CONFIRMATION,
    AWAITING_CORRECTION_FIELD,
    AWAITING_NEW_DRAFT_CONFIRMATION
}
