package pt.rucodel.productionplanning.domain;

public enum WhatsAppConversationState {
    AWAITING_DRIVER_NAME,
    AWAITING_PRODUCTION_SITE,
    AWAITING_CUSTOMER_NAME,
    AWAITING_CUSTOMER_OPTION,
    AWAITING_NEW_CUSTOMER_TAX_IDENTIFIER,
    AWAITING_NEW_CUSTOMER_COUNTRY,
    AWAITING_NEW_CUSTOMER_LOCALITY,
    AWAITING_NEW_CUSTOMER_CONFIRMATION,
    AWAITING_BIPARTITE_QUANTITY,
    AWAITING_WASHED_QUANTITY,
    AWAITING_NORMAL_QUANTITY,
    AWAITING_FACTORY_DROPOFF_DATE,
    AWAITING_FACTORY_DROPOFF_SLOT,
    AWAITING_READY_DATE,
    AWAITING_FACTORY_PICKUP_SLOT,
    AWAITING_NOTES,
    AWAITING_CONFIRMATION,
    IDLE
}
